subscription:
  channel: stable-v1.22
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cloud-native-postgresql.v1.22.3