apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: redis-schema
    files:
      - files/redis_schema.yaml
  - name: providerconfig
    files:
      - files/config.yaml
commonAnnotations:
  kustomize.config.k8s.io/behavior: replace
