apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redis-enterprise-operator-cert
spec:
  channel: production
  installPlanApproval: Automatic
  name: redis-enterprise-operator-cert
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redis-enterprise-operator.v7.2.4-2.0
