apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: rag-llm
patches:
  - target:
      kind: Deployment
      name: ui-multiprovider-rag-redis
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/0
      - op: remove
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
  - target:
      kind: Deployment
      name: ui-multiprovider-rag-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: redis://redis-stack-server:6379
  - target:
      kind: Deployment
      name: hf-text-generation-inference-server-model.*
    patch: |-
      - op: remove
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
  - target:
      kind: Job
      name: populate-vectordb
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/0
      - op: remove
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
  - target:
      kind: Job
      name: populate-vectordb
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: redis://redis-stack-server:6379
  - target:
      kind: PersistentVolumeClaim
      name: models-cache-model1
    patch: |-
      - op: remove
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
resources:
  - ../../base/deployments
  - ../../base/services
  - ../../base/configmaps
  - ../../base/persistentvolumeclaims
  - ../../base/routes
  - ../../base/jobs
# Overriding default RedisEnterprise installation
  - deployments/redis-stack-server.yaml
  - pvc/redis-stack-server.yaml
  - services/redis-stack-server.yaml
  - namespaces
secretGenerator:
  - name: huggingface-hub-token
    literals:
      - token=PLACEHOLDER
  - name: openai
    files:
      - secrets/files/openai_api_key.txt
