apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: rag-llm
resources:
  - ../../base/deployments
  - ../../base/services
  - ../../base/configmaps
  - ../../base/persistentvolumeclaims
  - ../../base/routes
  - ../../base/jobs
  - namespaces
