# Default values for edb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: "quay.io/enterprisedb/postgresql"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "16.2"

database: vectordb
owner: vectordb

storage:
  resizeInUseVolumes: true
  size: 10Gi

walStorage:
  resizeInUseVolumes: true
  size: 10Gi
